---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: 
  ioslides_presentation: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.

2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
library(tidyverse)
library(janitor)
library(here)
library(naniar)
```
```{r}
heartrate <- read_csv(here("data", "heartrate.csv"))
```
```{r}
names(heartrate)
```

For drug a:
```{r}
heartrate %>%
  ggplot(aes(x=patient, y=a, fill=patient))+
  geom_col()+
  labs(title="Comparison of Heartrate for Drug A",
       x="Patient", #or x=Null takes off patient label on x-axis
       y="Heartrate")
```

2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate %>%
  pivot_longer(-patient,
             names_to="drug",
             values_to="heartrate") %>% 
  ggplot(aes(x=drug, y=heartrate, fill=drug))+
  geom_boxplot(alpha=0.7)+  #the alpha adjusts transparency of color
  labs(title="Comparison of Heartbeat for each Drug for each Patient",
       x="Drugs",
       y="Heartbeat")
```